channel_sources:
  - conda-forge
channel_targets:
  - tiledb main
# build exactly what we need for TileDB Cloud
bzip2:
  - 1
c_compiler:
  - gcc
c_compiler_version:
  - 11
libcurl:
  - 8
libdeflate:
  - 1.17
  - 1.18
  - 1.19
openssl:
  - 3
xz:
  - 5
zlib:
  - 1.2
numpy:
  - 1.23
python:
  - 3.9.* *_cpython
python_impl:
  - cpython
