channel_sources:
  - tiledb,conda-forge,defaults
channel_targets:
  - tiledb main
numpy:
  - 1.20   # [not (osx and arm64)]
  - 1.20
  - 1.20
  - 1.21
python:
  - 3.7.* *_cpython   # [not (osx and arm64)]
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
python_impl:
  - cpython   # [not (osx and arm64)]
  - cpython
  - cpython
  - cpython
libdeflate:
  - 1.12
  - 1.13
  - 1.14
  - 1.16
  - 1.17
openssl:
  - 1.1.1
  - 3
