azure:
  build_id: 45
  user_or_org: TileDB-Inc
  project_name: CI
github:
  user_or_org: TileDB-Inc
  branch_name: main
  tooling_branch_name: main
provider:
  linux_64: azure
  osx_64: None
  win_64: None
upload_on_branch: main
